# Powerlevel10k configuration file
# Minimal prompt - current directory only
POWERLEVEL9K_MODE="compatible"

POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=""

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''

POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# Directory styling - clean and simple, no background
POWERLEVEL9K_DIR_FOREGROUND=39  # Blue text
POWERLEVEL9K_DIR_BACKGROUND=''
POWERLEVEL9K_DIR_HOME_FOREGROUND=39  # Blue text for home
POWERLEVEL9K_DIR_HOME_BACKGROUND=''
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=39
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=''
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=39
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=''
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_last"
